<a href="https://colab.research.google.com/github/trismegisto78/romeo/blob/master/my_romeo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/trismegisto78/romeo


Cloning into 'romeo'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 30 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (30/30), done.


In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM
import numpy as np

In [24]:
righe_file = open('romeo/strMacd2004_small.csv',encoding='utf-8',errors='ignore').read().split('\n')


TOT_WORDXROW = 100
MAX_INDEC = 10000
#len(righe_file)

nuoveRighe=[]
mappaDictionary = {}
dictionary = []
for i in range(0,MAX_INDEC):
  nuovaRiga=[]
  for x in range(i,i+TOT_WORDXROW):
    if i<(MAX_INDEC-TOT_WORDXROW):
      if righe_file[x] not in mappaDictionary:
        mappaDictionary[righe_file[x]]=1
        dictionary.append(int(righe_file[x]))
      nuovaRiga.append(int(righe_file[x]) )
  if len(nuovaRiga)>0:
    nuoveRighe.append(nuovaRiga)

dictionary.sort()

print(len(dictionary))



308


In [0]:
#word ti index map
word_to_index = {}

for i in range(len(dictionary)):
  word_to_index[ dictionary[i] ] = i

#print(word_to_index)

In [26]:
#transform in one hot vectors
righeHot = []
features = []

for riga in nuoveRighe:
  elementiHot = []
  for elem in riga:
    hotVec = np.zeros( len(dictionary) )
    hotVec[word_to_index[elem]] = 1
    elementiHot.append(hotVec)
  
  righeHot.append(elementiHot)

npRigheHot = np.array(righeHot)

for k in range(0,1):
   print(npRigheHot[k])



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:


max_features = len(dictionary)

model = Sequential()
model.add(Embedding(max_features, output_dim=256))
model.add(LSTM(128))
model.add(Dropout(0.5))
model.add(Dense(max_features, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])




In [0]:
for k in range(0,len(npRigheHot)-1) :
  model.fit(npRigheHot[k], npRigheHot[k+1], batch_size=16, epochs=10)
  #score = model.evaluate(x_test, y_test, batch_size=16)

